--- 
apiVersion: v1
kind: ReplicationController
metadata: 
  labels: 
    app: appdemo-rc
    dept: testing-rc
  name: dfinlayson-Rc
spec: 
  - 
    template: 
      metadata: 
        labels: 
          app: myapp-pod
          labels: FrontEndPod-pod
        name: myapp-pod
      spec: 
        containers: 
          - 
            image: nginx
            name: nginx-container-pod