--- 
apiVersion: v1
kind: ReplicationController
metadata:
  name: dfinlayson
  labels: 
    app: appdemo-rc
    dept: testing-rc
spec: 
  template:
    metadata: 
      name: myapp-pod   
      labels: 
        app: myapp-pod
        labels: FrontEndPod-pod    
    spec: 
      containers:
      - name: nginx-container-pod
        image: nginx
  replicas: 3 

